public class Main {
    public static void main(String[] args) {
System.out.println("задание 1");
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        System.out.println("задание 2");
        dog = dog + 4.0;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        System.out.println("задание 3");
dog = dog - 3.5;
System.out.println(dog);
cat = cat - 1.6;
System.out.println(cat);
paper = paper - 7639;
System.out.println(paper);
        System.out.println("задание 4");
var friends = 19;
System.out.println(friends);
friends = friends + 2;
System.out.println(friends);
friends = friends / 7;
System.out.println(friends);
        System.out.println("задание 5");
var frog = 3.5;
System.out.println(frog);
frog = frog * 10;
System.out.println(frog);
frog = frog / 3.5;
System.out.println(frog);
frog = frog + 4;
System.out.println(frog);
        System.out.println("задание 6");
var boxerWeight1 = 78.2;
System.out.println(boxerWeight1);
var boxerWeight2 = 82.7;
System.out.println(boxerWeight2);
var totalWeight = boxerWeight1 + boxerWeight2;
System.out.println("общий вес боксёров " + totalWeight + "кг");
var weightDifference = boxerWeight2 - boxerWeight1;
System.out.println("разница в весе " + weightDifference + "кг");
        System.out.println("задание 7");
        System.out.println("разница в весе, первый способ " + weightDifference + "кг");
        System.out.println("разница в весе, второй способ " + (boxerWeight2 % boxerWeight1) + "кг");
        System.out.println("задание 8");
var allTimes = 640;
System.out.println("всего " + allTimes + " часов");
var workerHour = 8;
System.out.println("один работник " + workerHour + " часов");
var allWorkers = (allTimes / workerHour);
System.out.println("всего работников в компании " + allWorkers + " человек");
allWorkers = allWorkers + 94;
System.out.println(allWorkers);
System.out.println("если в компании работает " + allWorkers + " человека, то всего " + (allWorkers * workerHour) + " часа работы может быть поделено между сотрудниками");
    }
}